# Site settings
title: Aaron Roberts
email: atr2982@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  For now it's just me, striving to become great at what I do. I want bigger things in life, but I love it when the inner kid takes command. It helps me find passion in what I do and what I create. I'm a current student at Full Sail University. Between class and work, I don't have much time to do any personal projects. In the future when I do, it will all be posted here! Stay Tuned!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: atr2982
github_username:  atr2982

# Build settings
markdown: kramdown
